/*
 * External User Management API
 * API for managing user information
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for EmailVerificationCodeAuthenticationRequest
 */
public class EmailVerificationCodeAuthenticationRequestTest {
    private final EmailVerificationCodeAuthenticationRequest model = new EmailVerificationCodeAuthenticationRequest();

    /**
     * Model tests for EmailVerificationCodeAuthenticationRequest
     */
    @Test
    public void testEmailVerificationCodeAuthenticationRequest() {
        // TODO: test EmailVerificationCodeAuthenticationRequest
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientSecret'
     */
    @Test
    public void clientSecretTest() {
        // TODO: test clientSecret
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'pendingAuthenticationToken'
     */
    @Test
    public void pendingAuthenticationTokenTest() {
        // TODO: test pendingAuthenticationToken
    }

}
