/*
 * External User Management API
 * API for managing user information
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for EmailVerificationRequiredResponse
 */
public class EmailVerificationRequiredResponseTest {
    private final EmailVerificationRequiredResponse model = new EmailVerificationRequiredResponse();

    /**
     * Model tests for EmailVerificationRequiredResponse
     */
    @Test
    public void testEmailVerificationRequiredResponse() {
        // TODO: test EmailVerificationRequiredResponse
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'pendingAuthenticationToken'
     */
    @Test
    public void pendingAuthenticationTokenTest() {
        // TODO: test pendingAuthenticationToken
    }

}
