/*
 * External User Management API
 * API for managing user information
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ListUsers200ResponseListMetadata
 */
public class ListUsers200ResponseListMetadataTest {
    private final ListUsers200ResponseListMetadata model = new ListUsers200ResponseListMetadata();

    /**
     * Model tests for ListUsers200ResponseListMetadata
     */
    @Test
    public void testListUsers200ResponseListMetadata() {
        // TODO: test ListUsers200ResponseListMetadata
    }

    /**
     * Test the property 'before'
     */
    @Test
    public void beforeTest() {
        // TODO: test before
    }

    /**
     * Test the property 'after'
     */
    @Test
    public void afterTest() {
        // TODO: test after
    }

}
