/*
 * External User Management API
 * API for managing user information
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.EmailVerificationCodeAuthenticationRequest;
import org.openapitools.client.model.PasswordAuthenticationRequest;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AuthenticateUserRequest
 */
@JsonPropertyOrder({
  AuthenticateUserRequest.JSON_PROPERTY_CLIENT_ID,
  AuthenticateUserRequest.JSON_PROPERTY_CLIENT_SECRET,
  AuthenticateUserRequest.JSON_PROPERTY_GRANT_TYPE,
  AuthenticateUserRequest.JSON_PROPERTY_EMAIL,
  AuthenticateUserRequest.JSON_PROPERTY_PASSWORD,
  AuthenticateUserRequest.JSON_PROPERTY_CODE,
  AuthenticateUserRequest.JSON_PROPERTY_PENDING_AUTHENTICATION_TOKEN
})
@JsonTypeName("authenticateUser_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AuthenticateUserRequest {
  public static final String JSON_PROPERTY_CLIENT_ID = "client_id";
  private String clientId;

  public static final String JSON_PROPERTY_CLIENT_SECRET = "client_secret";
  private String clientSecret;

  /**
   * The grant type of the application
   */
  public enum GrantTypeEnum {
    PASSWORD("password");

    private String value;

    GrantTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GrantTypeEnum fromValue(String value) {
      for (GrantTypeEnum b : GrantTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_GRANT_TYPE = "grant_type";
  private GrantTypeEnum grantType;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  private String password;

  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_PENDING_AUTHENTICATION_TOKEN = "pending_authentication_token";
  private String pendingAuthenticationToken;

  public AuthenticateUserRequest() {
  }

  public AuthenticateUserRequest clientId(String clientId) {
    
    this.clientId = clientId;
    return this;
  }

   /**
   * The client id of the application
   * @return clientId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientId() {
    return clientId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  public AuthenticateUserRequest clientSecret(String clientSecret) {
    
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * The client secret of the application
   * @return clientSecret
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CLIENT_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientSecret() {
    return clientSecret;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_SECRET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }


  public AuthenticateUserRequest grantType(GrantTypeEnum grantType) {
    
    this.grantType = grantType;
    return this;
  }

   /**
   * The grant type of the application
   * @return grantType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GRANT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GrantTypeEnum getGrantType() {
    return grantType;
  }


  @JsonProperty(JSON_PROPERTY_GRANT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGrantType(GrantTypeEnum grantType) {
    this.grantType = grantType;
  }


  public AuthenticateUserRequest email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * The user&#39;s email address
   * @return email
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(String email) {
    this.email = email;
  }


  public AuthenticateUserRequest password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * The user&#39;s password
   * @return password
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPassword(String password) {
    this.password = password;
  }


  public AuthenticateUserRequest code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * The verification code sent to the user&#39;s email address
   * @return code
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(String code) {
    this.code = code;
  }


  public AuthenticateUserRequest pendingAuthenticationToken(String pendingAuthenticationToken) {
    
    this.pendingAuthenticationToken = pendingAuthenticationToken;
    return this;
  }

   /**
   * The pending authentication token
   * @return pendingAuthenticationToken
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PENDING_AUTHENTICATION_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPendingAuthenticationToken() {
    return pendingAuthenticationToken;
  }


  @JsonProperty(JSON_PROPERTY_PENDING_AUTHENTICATION_TOKEN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPendingAuthenticationToken(String pendingAuthenticationToken) {
    this.pendingAuthenticationToken = pendingAuthenticationToken;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthenticateUserRequest authenticateUserRequest = (AuthenticateUserRequest) o;
    return Objects.equals(this.clientId, authenticateUserRequest.clientId) &&
        Objects.equals(this.clientSecret, authenticateUserRequest.clientSecret) &&
        Objects.equals(this.grantType, authenticateUserRequest.grantType) &&
        Objects.equals(this.email, authenticateUserRequest.email) &&
        Objects.equals(this.password, authenticateUserRequest.password) &&
        Objects.equals(this.code, authenticateUserRequest.code) &&
        Objects.equals(this.pendingAuthenticationToken, authenticateUserRequest.pendingAuthenticationToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, clientSecret, grantType, email, password, code, pendingAuthenticationToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthenticateUserRequest {\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    grantType: ").append(toIndentedString(grantType)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    pendingAuthenticationToken: ").append(toIndentedString(pendingAuthenticationToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

