/*
 * External User Management API
 * API for managing user information
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EmailVerificationRequiredResponse
 */
@JsonPropertyOrder({
  EmailVerificationRequiredResponse.JSON_PROPERTY_CODE,
  EmailVerificationRequiredResponse.JSON_PROPERTY_MESSAGE,
  EmailVerificationRequiredResponse.JSON_PROPERTY_EMAIL,
  EmailVerificationRequiredResponse.JSON_PROPERTY_PENDING_AUTHENTICATION_TOKEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EmailVerificationRequiredResponse {
  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_PENDING_AUTHENTICATION_TOKEN = "pending_authentication_token";
  private String pendingAuthenticationToken;

  public EmailVerificationRequiredResponse() {
  }

  public EmailVerificationRequiredResponse code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(String code) {
    this.code = code;
  }


  public EmailVerificationRequiredResponse message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(String message) {
    this.message = message;
  }


  public EmailVerificationRequiredResponse email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }


  public EmailVerificationRequiredResponse pendingAuthenticationToken(String pendingAuthenticationToken) {
    
    this.pendingAuthenticationToken = pendingAuthenticationToken;
    return this;
  }

   /**
   * Get pendingAuthenticationToken
   * @return pendingAuthenticationToken
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PENDING_AUTHENTICATION_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPendingAuthenticationToken() {
    return pendingAuthenticationToken;
  }


  @JsonProperty(JSON_PROPERTY_PENDING_AUTHENTICATION_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPendingAuthenticationToken(String pendingAuthenticationToken) {
    this.pendingAuthenticationToken = pendingAuthenticationToken;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailVerificationRequiredResponse emailVerificationRequiredResponse = (EmailVerificationRequiredResponse) o;
    return Objects.equals(this.code, emailVerificationRequiredResponse.code) &&
        Objects.equals(this.message, emailVerificationRequiredResponse.message) &&
        Objects.equals(this.email, emailVerificationRequiredResponse.email) &&
        Objects.equals(this.pendingAuthenticationToken, emailVerificationRequiredResponse.pendingAuthenticationToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, email, pendingAuthenticationToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailVerificationRequiredResponse {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    pendingAuthenticationToken: ").append(toIndentedString(pendingAuthenticationToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

