/*
 * External User Management API
 * API for managing user information
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListUsers200ResponseListMetadata;
import org.openapitools.client.model.User;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ListUsers200Response
 */
@JsonPropertyOrder({
  ListUsers200Response.JSON_PROPERTY_DATA,
  ListUsers200Response.JSON_PROPERTY_LIST_METADATA
})
@JsonTypeName("listUsers_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-03T15:32:47.282696Z[Europe/London]")
public class ListUsers200Response {
  public static final String JSON_PROPERTY_DATA = "data";
  private List<User> data;

  public static final String JSON_PROPERTY_LIST_METADATA = "list_metadata";
  private ListUsers200ResponseListMetadata listMetadata;

  public ListUsers200Response() {
  }

  public ListUsers200Response data(List<User> data) {
    
    this.data = data;
    return this;
  }

  public ListUsers200Response addDataItem(User dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<User> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(List<User> data) {
    this.data = data;
  }


  public ListUsers200Response listMetadata(ListUsers200ResponseListMetadata listMetadata) {
    
    this.listMetadata = listMetadata;
    return this;
  }

   /**
   * Get listMetadata
   * @return listMetadata
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIST_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ListUsers200ResponseListMetadata getListMetadata() {
    return listMetadata;
  }


  @JsonProperty(JSON_PROPERTY_LIST_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setListMetadata(ListUsers200ResponseListMetadata listMetadata) {
    this.listMetadata = listMetadata;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListUsers200Response listUsers200Response = (ListUsers200Response) o;
    return Objects.equals(this.data, listUsers200Response.data) &&
        Objects.equals(this.listMetadata, listUsers200Response.listMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, listMetadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListUsers200Response {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    listMetadata: ").append(toIndentedString(listMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

